language: python

cache: pip

matrix:
    include:
        - python: 2.7
          env: TOX_ENV=py27
        - python: 3.4
          env: TOX_ENV=py34
        - python: 3.5
          env: TOX_ENV=py35
        - python: 2.7
          env: TOX_ENV=pep8
        - python: 3.4
          env: TOX_ENV=py3pep8

addons:
  apt:
    packages:
    - freetds-dev
install:
  - pip install -r requirements.txt
  - pip install -r tox-requirements.txt
script:
  - tox -e $TOX_ENV -- $TOX_FLAGS
after_success:
  - coveralls
